### ISSUE TITLE
Save parameters as presets?

### ISSUE THREAD

**Issue by frescoalfredo** [ReaCoMa/ReaCoMa-2.0#1]
I'm primarily using HPSS right now and although it works very well, finding the right settings is a matter of trial-and-error. I'd like to request, if possible, that the script allows saving of all parameters as presets which can be recalled. (Currently I'm taking screen shots of the script window as reference for settings that work well for a given audio source type, which is better than nothing.) Since the script window recalls the previous settings used (as long as Reaper isn't closed), I could fumble my way through changing parameters and then once I've gotten a result I like, I could open the window again and save a preset. Naming of the presets would be helpful too.

Another request, which might be too far beyond the scope of what you planned: allowing auditioning of the script's results before outputting WAV files (for a single item that's chosen, anyway). This would make parameter selection significantly faster.

There are some Reascript GUI toolkits and API extensions to take advantage of, if you are considering this kind of thing. I can link you to them if you're not aware of them already.

**Comment by jamesb93** [comment]
There is a new release of ReaImGui. If you wanted to try out the installation to find any warts/issues that would be amazing! It's working my end though so far :)

**Comment by JamesPeters667** [comment]
It seems to work well, from the little bit of testing I did with HPSS. It's nice to move sliders around and not have to enter values especially with commas between them on a single line. I suppose it'd be nice if the hints ("?") would provide a bit more useful information about all parameters, since a lot of this is guesswork as I'm doing it. But if the original documentation isn't clear enough about it (from what I've seen), that probably won't happen. :)
