### ISSUE TITLE
scripts not executing 

### ISSUE THREAD

**Issue by jmarcham1983** [ReaCoMa/ReaCoMa-2.0#3]
first off just a few specs for you

OS  MX linux ( debian 10 buster)

reaper version 6.42

the gui for reacoma 2 and the older version reacoma 1 load up, it finds the executables when I link the address but i get this error (copied from terminal)

console output

/home/xylem/Samples/Drum loops/electro loops/me_drum_loop_funk_kick_snare_115.wav161843527709811fs.csv could not be read because it does not exist.
stack traceback:
	...e/xylem/.config/REAPER/Scripts/ReaCoMa-2.0/lib/utils.lua:128: in function 'utils.assert'
	...e/xylem/.config/REAPER/Scripts/ReaCoMa-2.0/lib/utils.lua:254: in function 'utils.readfile'
	...APER/Scripts/ReaCoMa-2.0/lib/algorithms/noveltyslice.lua:45: in function 'algorithms/noveltyslice.perform_update'
	....config/REAPER/Scripts/ReaCoMa-2.0/lib/imgui_helpers.lua:76: in function 'imgui_helpers.process'
	....config/REAPER/Scripts/ReaCoMa-2.0/lib/imgui_wrapper.lua:100: in function 'imgui_wrapper.loop'
	....config/REAPER/Scripts/ReaCoMa-2.0/lib/imgui_wrapper.lua:118: in function <....config/REAPER/Scripts/ReaCoMa-2.0/lib/imgui_wrapper.lua:117>
ImGui assertion failed: (g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?"

hope you can help, this looks like a fascinating tool

**Comment by jamesb93** [comment]
Hey,

Not sure why this is happening. I've not tested on debian 10, nor compiled the CLI tools there before. Can you verify the command line tools can normally process files for me? Would be something like running:

`fluid-hpss -source somefile.wav -harmonic output.wav`

and checking that runs.

**Comment by chailight** [comment]
I'm getting the same behaviour. I checked the command line and you suggested above and that works fine. Would love to switch up to ReaCoMa 2.0 as the gui makes things much easier. let me know if there's any quick fix, or something you'd like me to test

Using latest version of Reaper on a Mac running 10.14.6

**Comment by jamesb93** [comment]
Hello again,

It's definitely something I broke but I just haven't got time to fix it right now. It's likely a trivial error somewhere in each algorithm's method that creates the string which is passed over to the command-line if you wanted to take a look. Otherwise I should fix this in the next fortnight or so.

**Comment by jamesb93** [comment]
I've located the issue @chailight and it's the fact that we now deal with "maximum" parameters differently as of the beta7 version. So the CLI is expected something like `harmfiltersize 4 4` instead of just `harmfiltersize 4`. The former makes more sense in the context of SuperCollider (where you would define them as such) and where you can modulate up to the maximum that parameter in realtime. The CLI though has no such use case and should, IMO, just extract the maximum value from the setting itself. I should have a fix for this pretty imminently. For now you can use this branch which has it fixed:

https://github.com/ReaCoMa/ReaCoMa-2.0/tree/beta7-updates

**Comment by jamesb93** [comment]
Actually the main branch now has the changes!
