### ISSUE TITLE
Congrats and Reapack question

### ISSUE THREAD

**Issue by AlbertoV5** [ReaCoMa/ReaCoMa-2.0#8]
Just tried Reacoma in a few samples and it's just what I needed. Had this type of functionality on the back of my mind since using librosa a few years ago and this looks like a clean and powerful algorithm+implementation. Congratulations and thank you! (I'll donate as soon as I can).

Now my question is if the Reapack version is maintained or updated frequently as it is a nice way to manage Reaper extension for me, or should I just go with the main branch instead?

Thanks.

**Comment by jamesb93** [comment]
Hey!

Thanks for the kind words.

The ReaPack version was me experimenting with how I would need to restructure the code in order to make it "compliant" with the structure that ReaPack expects. I aim to do this at some point but it is a commitment to a structure which I'm not decided on how happy I am yet.

Out of curiosity would ReaPack support be a big boon for someone like yourself?

**Comment by jamesb93** [comment]
> It's always nice to have and it may be easier to share with other Reaper users but for me works alright as it is right now.

Cool, good to know.
